package com.myspace.variousmultipletracker;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Alert implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String symbol;
	private java.lang.Double standardDeviation;
	private java.lang.Double variance;
	private java.lang.Double min;
	private java.lang.Double max;
	private java.lang.Double avg;

	public Alert() {
	}

	public java.lang.String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(java.lang.String symbol) {
		this.symbol = symbol;
	}

	public java.lang.Double getStandardDeviation() {
		return this.standardDeviation;
	}

	public void setStandardDeviation(java.lang.Double standardDeviation) {
		this.standardDeviation = standardDeviation;
	}

	public java.lang.Double getVariance() {
		return this.variance;
	}

	public void setVariance(java.lang.Double variance) {
		this.variance = variance;
	}

	public java.lang.Double getMin() {
		return this.min;
	}

	public void setMin(java.lang.Double min) {
		this.min = min;
	}

	public java.lang.Double getMax() {
		return this.max;
	}

	public void setMax(java.lang.Double max) {
		this.max = max;
	}

	public java.lang.Double getAvg() {
		return this.avg;
	}

	public void setAvg(java.lang.Double avg) {
		this.avg = avg;
	}

	public Alert(java.lang.String symbol, java.lang.Double standardDeviation,
			java.lang.Double variance, java.lang.Double min,
			java.lang.Double max, java.lang.Double avg) {
		this.symbol = symbol;
		this.standardDeviation = standardDeviation;
		this.variance = variance;
		this.min = min;
		this.max = max;
		this.avg = avg;
	}

}