package com.myspace.variousmultipletracker;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ComparableFirmsMultiple implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double pe;
	private double ps;
	@org.kie.api.definition.type.Label("mtb")
	private double mtb;
	private double pocf;
	@org.kie.api.definition.type.Label("prandd")
	private double prandd;

	private java.lang.String symbol;

	public ComparableFirmsMultiple() {
	}

	public double getPe() {
		return this.pe;
	}

	public void setPe(double pe) {
		this.pe = pe;
	}

	public double getPs() {
		return this.ps;
	}

	public void setPs(double ps) {
		this.ps = ps;
	}

	public double getMtb() {
		return this.mtb;
	}

	public void setMtb(double mtb) {
		this.mtb = mtb;
	}

	public double getPocf() {
		return this.pocf;
	}

	public void setPocf(double pocf) {
		this.pocf = pocf;
	}

	public double getPrandd() {
		return this.prandd;
	}

	public void setPrandd(double prandd) {
		this.prandd = prandd;
	}

	public java.lang.String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(java.lang.String symbol) {
		this.symbol = symbol;
	}

	public ComparableFirmsMultiple(double pe, double ps, double mtb,
			double pocf, double prandd, java.lang.String symbol) {
		this.pe = pe;
		this.ps = ps;
		this.mtb = mtb;
		this.pocf = pocf;
		this.prandd = prandd;
		this.symbol = symbol;
	}

}