package com.myspace.variousmultipletracker;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EstimatedPrice implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double pe;
	private double ps;
	private double mtb;
	@org.kie.api.definition.type.Label("pocf")
	private double pocf;
	private double average;

	private java.lang.Double prandd;

	private java.lang.String symbol;

	public EstimatedPrice() {
	}

	public double getPe() {
		return this.pe;
	}

	public void setPe(double pe) {
		this.pe = pe;
	}

	public double getPs() {
		return this.ps;
	}

	public void setPs(double ps) {
		this.ps = ps;
	}

	public double getMtb() {
		return this.mtb;
	}

	public void setMtb(double mtb) {
		this.mtb = mtb;
	}

	public double getPocf() {
		return this.pocf;
	}

	public void setPocf(double pocf) {
		this.pocf = pocf;
	}

	public double getAverage() {
		return this.average;
	}

	public void setAverage(double average) {
		this.average = average;
	}

	public java.lang.Double getPrandd() {
		return this.prandd;
	}

	public void setPrandd(java.lang.Double prandd) {
		this.prandd = prandd;
	}

	public java.lang.String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(java.lang.String symbol) {
		this.symbol = symbol;
	}

	public EstimatedPrice(double pe, double ps, double mtb, double pocf,
			double average, java.lang.Double prandd, java.lang.String symbol) {
		this.pe = pe;
		this.ps = ps;
		this.mtb = mtb;
		this.pocf = pocf;
		this.average = average;
		this.prandd = prandd;
		this.symbol = symbol;
	}

}