package com.myspace.variousmultipletracker;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class StandAndPoors200 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "security")
	private java.lang.String security;
	@org.kie.api.definition.type.Label(value = "symbol")
	private java.lang.String symbol;
	@org.kie.api.definition.type.Label(value = "GICSSector")
	private java.lang.String GICSSector;
	@org.kie.api.definition.type.Label(value = "GICSSubSector")
	private java.lang.String GICSSubSector;
	@org.kie.api.definition.type.Label(value = "headquaterCity")
	private java.lang.String headquaterCity;
	@org.kie.api.definition.type.Label(value = "headquaterCountry")
	private java.lang.String headquaterCountry;
	@org.kie.api.definition.type.Label(value = "CIK")
	private java.lang.String CIK;

	public StandAndPoors200() {
	}

	public java.lang.String getSecurity() {
		return this.security;
	}

	public void setSecurity(java.lang.String security) {
		this.security = security;
	}

	public java.lang.String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(java.lang.String symbol) {
		this.symbol = symbol;
	}

	public java.lang.String getGICSSector() {
		return this.GICSSector;
	}

	public void setGICSSector(java.lang.String GICSSector) {
		this.GICSSector = GICSSector;
	}

	public java.lang.String getGICSSubSector() {
		return this.GICSSubSector;
	}

	public void setGICSSubSector(java.lang.String GICSSubSector) {
		this.GICSSubSector = GICSSubSector;
	}

	public java.lang.String getHeadquaterCity() {
		return this.headquaterCity;
	}

	public void setHeadquaterCity(java.lang.String headquaterCity) {
		this.headquaterCity = headquaterCity;
	}

	public java.lang.String getHeadquaterCountry() {
		return this.headquaterCountry;
	}

	public void setHeadquaterCountry(java.lang.String headquaterCountry) {
		this.headquaterCountry = headquaterCountry;
	}

	public java.lang.String getCIK() {
		return this.CIK;
	}

	public void setCIK(java.lang.String CIK) {
		this.CIK = CIK;
	}

	public StandAndPoors200(java.lang.String security, java.lang.String symbol,
			java.lang.String GICSSector, java.lang.String GICSSubSector,
			java.lang.String headquaterCity,
			java.lang.String headquaterCountry, java.lang.String CIK) {
		this.security = security;
		this.symbol = symbol;
		this.GICSSector = GICSSector;
		this.GICSSubSector = GICSSubSector;
		this.headquaterCity = headquaterCity;
		this.headquaterCountry = headquaterCountry;
		this.CIK = CIK;
	}

}