package com.myspace.variousmultipletracker;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TargetCompanyList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("TargetList")
	private java.util.List<com.myspace.variousmultipletracker.TargetCompany> targetList;

	@org.kie.api.definition.type.Label(value = "targetSymbol")
	private java.lang.String targetSymbol;

	public TargetCompanyList() {
	}

	public java.util.List<com.myspace.variousmultipletracker.TargetCompany> getTargetList() {
		return this.targetList;
	}

	public void setTargetList(
			java.util.List<com.myspace.variousmultipletracker.TargetCompany> targetList) {
		this.targetList = targetList;
	}

	public java.lang.String getTargetSymbol() {
		return this.targetSymbol;
	}

	public void setTargetSymbol(java.lang.String targetSymbol) {
		this.targetSymbol = targetSymbol;
	}

	public TargetCompanyList(
			java.util.List<com.myspace.variousmultipletracker.TargetCompany> targetList,
			java.lang.String targetSymbol) {
		this.targetList = targetList;
		this.targetSymbol = targetSymbol;
	}

}