package com.myspace.variousmultipletracker;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TargetFirm implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private double price;
	@org.kie.api.definition.type.Label("noOfShares")
	private double noOfShares;
	@org.kie.api.definition.type.Label("eps")
	private double eps;
	@org.kie.api.definition.type.Label("rps")
	private double rps;
	@org.kie.api.definition.type.Label("bvps")
	private double bvps;
	@org.kie.api.definition.type.Label("osps")
	private double ocps;

	private java.lang.Double randd;

	private java.lang.String symbol;

	public TargetFirm() {
	}

	public double getNoOfShares() {
		return this.noOfShares;
	}

	public void setNoOfShares(double noOfShares) {
		this.noOfShares = noOfShares;
	}

	public double getEps() {
		return this.eps;
	}

	public void setEps(double eps) {
		this.eps = eps;
	}

	public double getRps() {
		return this.rps;
	}

	public void setRps(double rps) {
		this.rps = rps;
	}

	public double getBvps() {
		return this.bvps;
	}

	public void setBvps(double bvps) {
		this.bvps = bvps;
	}

	public double getOcps() {
		return this.ocps;
	}

	public void setOcps(double ocps) {
		this.ocps = ocps;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public java.lang.Double getRandd() {
		return this.randd;
	}

	public void setRandd(java.lang.Double randd) {
		this.randd = randd;
	}

	public java.lang.String getSymbol() {
		return this.symbol;
	}

	public void setSymbol(java.lang.String symbol) {
		this.symbol = symbol;
	}

	public TargetFirm(double price, double noOfShares, double eps, double rps,
			double bvps, double ocps, java.lang.Double randd,
			java.lang.String symbol) {
		this.price = price;
		this.noOfShares = noOfShares;
		this.eps = eps;
		this.rps = rps;
		this.bvps = bvps;
		this.ocps = ocps;
		this.randd = randd;
		this.symbol = symbol;
	}

}